config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "custom_registration"}

  resources :users,       only: [:index,  :show]
  resources :friendships, only: [:create, :update, :destroy]
  resources :posts,       only: [:index,  :create, :destroy]
  resources :likes,       only: [:create, :destroy]
  resources :comments,    only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post, optional: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :sender,     class_name: "User", optional: true
  belongs_to :receiver,   class_name: "User", optional: true
  belongs_to :friend,     class_name: "User", optional: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, inverse_of: :likes
  belongs_to :post, inverse_of: :likes
  # make sure the user can only follow a post no more than once.
  validates :user_id, uniqueness: {scope: :post_id}  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author,           class_name: "User",
                                foreign_key: "user_id"
  has_many :likes,              inverse_of: :post,    # bi directional assocation.
                                dependent: :destroy
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sent_friend_requests,     class_name: "Friendship",
                                      foreign_key: "sender_id",
                                      dependent: :destroy
  has_many :received_friend_requests, class_name: "Friendship",
                                      foreign_key: "receiver_id",
                                      dependent: :destroy
  has_many :friendships
  has_many :friends,                  through: :friendships,
                                      source: :friend,
                                      dependent: :destroy
  has_many :posts
  has_many :likes,                    inverse_of: :user,    # bi directoinal assocation
                                      dependent: :destroy
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable # :trackable, :validatable

 def add_friend(new_friend)
   if !self.friends.include?(new_friend)
     self.friends << new_friend
   else
     return
   end
 end

 def friends?(friend)
   self.friends.exists?(friend.id)
 end

 def delete_friend_request(friend_request)
   self.sent_friend_requests.delete(friend_request)
 end

 def self.from_omniauth(auth)
   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
   end
 end

 def self.new_with_session(params, session)
   super.tap do |user|
     if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
       user.email = data["email"] if user.email.blank?
     end
   end
 end

 def password_required?
   super && provider.blank?
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = current_user.comments.build(comment_params)
    if comment.save
      flash[:notice] = "Comment Posted"
    else
      flash[:alert] = "Failed to post comment" 
    end
    redirect_to current_user
  end

  def destroy
    comment = current_user.comments.find(params[:id])
    if comment.destroy
      flash[:notice] = "deleted comment"
    else
      flash[:alert] = "cannot delete comment"
    end
    redirect_to current_user
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = current_user.sent_friend_requests.build(friendship_params)
    if @friendship.save
      flash[:notice] = "Friend request sent"
    else
      flash[:alert] = "Friend request failed"
    end
    redirect_to root_path
  end

  def update
    @friendship = current_user.sent_friend_requests.where(sender_id: params[:sender_id], receiver_id: params[:receiver_id]).first
    @friendship = Friendship.where(sender_id: params[:sender_id], receiver_id: params[:receiver_id]).first if !@friendship
    if @friendship.save
      @friendship.update_attributes(accepted: true)
      current_user.add_friend(@friendship.sender)
      @friendship.sender.add_friend(current_user)
      current_user.delete_friend_request(@friendship)
      flash[:notice] = "Friend added"
    else
      flash[:alert] = "Cannot add friend"
    end
    redirect_to current_user
  end

  def destroy
    @friendship = Friendship.where(sender_id: params[:sender_id], receiver_id: params[:receiver_id]).first
    if @friendship.destroy
      flash[:notice] = "denied friend request"
    else
      flash[:alert] = "failed to destroy"
    end
    redirect_to current_user
  end

  private

  def friendship_params
    params.permit(:sender_id, :receiver_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = current_user.likes.build(like_params)
    if like.save
      flash[:notice] = "You have liked the post"
    else
      flash[:alert] = "Failed to like post"
    end
    redirect_to current_user
  end

  def destroy
    like = Like.where(user_id: params[:user_id], post_id: params[:post_id]).first
    if like.destroy
      flash[:notice] = "Unliked post"
    else
      flash[:notice] = "Failed to unliked post"
    end
    redirect_to current_user
  end

  private

  def like_params
    params.permit(:post_id)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(current_user.id)
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = "Post created"
    else
      flash[:alert] = "Post creation failed"
    end
    redirect_to current_user
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "Post '#{@post.title}' deleted"
    else
      flash[:alert] = "Couln't delete '#{@post.title}' deleted"
    end
    redirect_to current_user
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.paginate(page: params[:page], per_page: 5)
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/custom_registration_helper.rb
module CustomRegistrationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.email)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" %>
  </head>

  <body>
    <div class="container">
      <%= render "partials/navbar" %>

      <% if flash[:notice]  %>
        <span class="alert alert-success"><%= notice %></span>
      <% elsif flash[:alert]%>      
        <span class="alert alert-danger"><%= alert %></span>
      <% end %>

      <main>
        <%= yield %>
      </main>

      <%= render "partials/footer" %>
    </div>
  </body>
</html>

app/views/partials/_comments_form.html.erb
<%= form_for current_user.comments.build, html: { id: "comment_form" } do |f| %>
  <%= f.text_area :content, size: "45x1", class: "form-control", placeholder: "Enter Comment" %>
  <%= f.hidden_field :post_id, value: locals[:friend_post_id] %>

  <%= f.submit "Post", class: "btn btn-primary btn-xs comment-form-submit-btn" %>

<% end %>

app/views/partials/_footer.html.erb
<footer>
  Copyright &copy; 2019 Ben Garcia
  <a href="https://github.com/ben-garcia/odin_facebook/">
    View Code
  </a>
</footer>

app/views/partials/_navbar.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">OdinFacebook</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "All Users", users_path %></li>
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <li><%= link_to "My Posts", posts_path %></li>
        <li class="align-with-navbar">FR Pending:
          <span class="badge-num badge">
            <%= link_to "#{current_user.received_friend_requests.count}", user_path(current_user) %>
          </span>
        </li>
        <li class="align-with-nav">Logged In as: <strong><%= current_user.email %></strong></li>
      </ul>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Settings", edit_user_registration_path, class: "glyphicon glyphicon-cog" %></li>
        <li><%= link_to "LogOut", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-off" %></li>
      </ul>
    </div>
  </div>
  </nav>
<% else %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">OdinFacebook</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "LogIn", new_user_session_path, class: "glyphicon glyphicon-log-in" %></li>
        <li><%= link_to "SignUp", new_user_registration_path, class: "glyphicon glyphicon-plus" %></li>
      </ul>
    </div>
  </div>
</nav>
<% end %>

app/views/partials/_posts.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="">
      <h2>Your Posts</h2>
    </div>

    <% if @user.posts.any? %>
    <div>
      <% @user.posts.each do |post| %>
        <article class="col-xm-12 col-sm-12 col-md-6 well">
          <h3 class="col-xm-12 col-sm-12 col-md-12"><%= post.title %></h3>
          <p class="col-sm-12 col-sm-12 col-md-12"><%= post.content %></p>
          <span class="">
            <%=
              link_to "Delete",
              post_path(id: post.id),
              method: :delete,
              class: "btn btn-danger delete_post"
            %>
          </span>
        </article> 
      <% end %>
    </div>
    <% else %>
      <p>No Posts Yet</p>
    <% end %>
  </div>
</div>

app/views/shared/_comments_form.html.erb
<%= form_for current_user.comments.build do |f| %>
  <%= f.text_area :content, size: "45x1" %>
  <%= f.hidden_field :post_id, value: locals[:friend_post_id] %>

  <%= f.submit "Post Comment" %>

<% end %>