config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "custom_registration"}

  resources :users,       only: [:index,  :show]
  resources :friendships, only: [:create, :update, :destroy]
  resources :posts,       only: [:index,  :create, :destroy]
  resources :likes,       only: [:create, :destroy]
  resources :comments,    only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post, optional: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :sender,     class_name: "User", optional: true
  belongs_to :receiver,   class_name: "User", optional: true
  belongs_to :friend,     class_name: "User", optional: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, inverse_of: :likes
  belongs_to :post, inverse_of: :likes
  # make sure the user can only follow a post no more than once.
  validates :user_id, uniqueness: {scope: :post_id}  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author,           class_name: "User",
                                foreign_key: "user_id"
  has_many :likes,              inverse_of: :post,    # bi directional assocation.
                                dependent: :destroy
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sent_friend_requests,     class_name: "Friendship",
                                      foreign_key: "sender_id",
                                      dependent: :destroy
  has_many :received_friend_requests, class_name: "Friendship",
                                      foreign_key: "receiver_id",
                                      dependent: :destroy
  has_many :friendships
  has_many :friends,                  through: :friendships,
                                      source: :friend,
                                      dependent: :destroy
  has_many :posts
  has_many :likes,                    inverse_of: :user,    # bi directoinal assocation
                                      dependent: :destroy
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable # :trackable, :validatable

 def add_friend(new_friend)
   if !self.friends.include?(new_friend)
     self.friends << new_friend
   else
     return
   end
 end

 def friends?(friend)
   self.friends.exists?(friend.id)
 end

 def delete_friend_request(friend_request)
   self.sent_friend_requests.delete(friend_request)
 end

 def self.from_omniauth(auth)
   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
   end
 end

 def self.new_with_session(params, session)
   super.tap do |user|
     if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
       user.email = data["email"] if user.email.blank?
     end
   end
 end

 def password_required?
   super && provider.blank?
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = current_user.comments.build(comment_params)
    if comment.save
      flash[:notice] = "Comment Posted"
    else
      flash[:alert] = "Failed to post comment" 
    end
    redirect_to current_user
  end

  def destroy
    comment = current_user.comments.find(params[:id])
    if comment.destroy
      flash[:notice] = "deleted comment"
    else
      flash[:alert] = "cannot delete comment"
    end
    redirect_to current_user
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/custom_registration_controller.rb
class CustomRegistrationController < Devise::RegistrationsController
  def create
    super
    if @user.persisted?
      # UsersMailer.welcome_email(@user).deliver_now
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = current_user.sent_friend_requests.build(friendship_params)
    if @friendship.save
      flash[:notice] = "Friend request sent"
    else
      flash[:alert] = "Friend request failed"
    end
    redirect_to root_path
  end

  def update
    @friendship = current_user.sent_friend_requests.where(sender_id: params[:sender_id], receiver_id: params[:receiver_id]).first
    @friendship = Friendship.where(sender_id: params[:sender_id], receiver_id: params[:receiver_id]).first if !@friendship
    if @friendship.save
      @friendship.update_attributes(accepted: true)
      current_user.add_friend(@friendship.sender)
      @friendship.sender.add_friend(current_user)
      current_user.delete_friend_request(@friendship)
      flash[:notice] = "Friend added"
    else
      flash[:alert] = "Cannot add friend"
    end
    redirect_to current_user
  end

  def destroy
    @friendship = Friendship.where(sender_id: params[:sender_id], receiver_id: params[:receiver_id]).first
    if @friendship.destroy
      flash[:notice] = "denied friend request"
    else
      flash[:alert] = "failed to destroy"
    end
    redirect_to current_user
  end

  private

  def friendship_params
    params.permit(:sender_id, :receiver_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = current_user.likes.build(like_params)
    if like.save
      flash[:notice] = "You have liked the post"
    else
      flash[:alert] = "Failed to like post"
    end
    redirect_to current_user
  end

  def destroy
    like = Like.where(user_id: params[:user_id], post_id: params[:post_id]).first
    if like.destroy
      flash[:notice] = "Unliked post"
    else
      flash[:notice] = "Failed to unliked post"
    end
    redirect_to current_user
  end

  private

  def like_params
    params.permit(:post_id)
  end


end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    # You need to implement the method below in you model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, notice: "Signed in!"
    else
      session["devise.user_attributes"] = request.env["omniath.auth"]
      redirect_to new_user_registration_url
    end
  end
  alias_method :facebook, :all
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(current_user.id)
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = "Post created"
    else
      flash[:alert] = "Post creation failed"
    end
    redirect_to current_user
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "Post '#{@post.title}' deleted"
    else
      flash[:alert] = "Couln't delete '#{@post.title}' deleted"
    end
    redirect_to current_user
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.paginate(page: params[:page], per_page: 5)
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/custom_registration_helper.rb
module CustomRegistrationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.email)
  end
end

app/views/posts/index.html.erb
<%= render "partials/posts" %>

<div class="row">
  <div class="cols-xs-12 col-sm-12 col-md-6">
    <div>
      <h2>Create New Post</h2>
    </div>
    <%= form_for @user.posts.build do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %><br><br>

      <%= f.label :content %>
      <%= f.text_area :content, size: "30x5", class: "form-control"%><br><br>

      <%= f.submit "Create Post", class: "btn btn-primary"%><br><br>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div>
      <h2>Your Friends Posts</h2>
    </div>

  <% if @user.friends.any? %>
    <% @user.friends.each do |friend| %>
      <% if friend.posts.any? %>
        <% friend.posts.each do |friend_post| %>
        <article>
          <div class="well">
            <h3 class="post__title"><%= friend_post.title %></h3> 
            By
            <span class="post__author"><%= friend_post.author.email %></span>
            <p><%= friend_post.content %></p>
            <span> 
              <i class="glyphicon glyphicon-thumbs-up thumbs-up"></i>
              <%= friend_post.likes.count %>
            </span>
            <% if !friend_post.likes.exists?(user_id: current_user.id) %>
              <span>
                <%=
                  link_to "Like",
                  likes_path(post_id: friend_post.id),
                  method: :post,
                  class: "btn btn-success btn-xs",
                  remote: true
                %>
              </span>
            <% else %>
              <span>
                <%=
                  link_to "Unlike",
                  like_path(id: friend_post.id, user_id: current_user.id, post_id: friend_post.id),
                  method: :delete,
                  class: "btn btn-danger btn-xs"
                %>
              </span>
            <% end %>
          </div>

          <span class="view-comments">
            <% if friend_post.comments.any? %>
              View all <%= friend_post.comments.size %> comments
              <i class="glyphicon glyphicon-chevron-down"></i>
            <% else %>
              This post doesn't any comments yet!<br /> Be the one to post the first.
              <i class="glyphicon glyphicon-chevron-down"></i>
            <% end %>
          </span>

          <div class="comments">
            <%= render "partials/comments_form", locals: { friend_post_id: friend_post.id } %>
            <% if friend_post.comments.any? %>
              <% friend_post.comments.each do |comment| %>
                <div class="single-comment">
                  <span class="comment-author"><%= comment.user.email %></span><br />
                  <%= comment.content %>
                  <% if current_user == comment.user %>
                  <%= link_to "Delete", comment_path(id: comment.id), method: :delete, class: "btn btn-xs btn-danger" %>
                <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </article>
        <% end %>
      <% end %>
    <% end %>
  <% end %>

  </div>
</div>

app/views/users/index.html.erb
<div>

  <h1>Users</h1>
</div>

<%= will_paginate @users %>

<div> 
  <% @users.each do |user| %>
    <article class="row well">
      <span class="col-xs-12 col-sm-12 col-md-4">
        <%= gravatar_for user %>
      </span> 
      <% if current_user != user %>
        <span class="col-xs-12 col-sm-12 col-md-4">
          <%= user.email %> 
        </span>
        <% if !current_user.sent_friend_requests.exists?(receiver_id: user.id) && !current_user.friends?(user) %>
          <div class="col-xs-12 col-sm-12 col-md-4 btn btn-primary">
            <%= link_to "Send Friend Request",
                friendships_path(sender_id: current_user.id,
                                 receiver_id: user.id),
                method: :post,
                class: "button__text" %>
          </div>
        <% end %>
      <% end %>

    </article>
  <% end %>

</div>
<%= will_paginate @users %>

</div>

app/views/users/show.html.erb
<div class="jumbotron">
  <h1><strong><%= @user.email %></strong>'s Page</h1>
  <%= gravatar_for @user %><br><br>
  Email: <strong><%= @user.email %></strong><br><br>
  Joined On: <strong><%= @user.created_at %></strong><br><br>
</div>

<!-- This row contains the users pending friend requests and their requests sent. -->
<section class="row">
  <!-- Users pending friend requets-->
  <div class="col-xs-12 col-sm-12 col-md-6">
    <h2>Friend Requests Pending</h2>

    <% if @user.received_friend_requests.any? %>
      <% @user.received_friend_requests.each do |request| %>
        <article>
          <span><%= request.sender.email %></span>
          <span>
            <%= link_to "Accept", friendship_path(sender_id: request.sender.id, receiver_id: current_user.id), method: :patch, class: "btn btn-success" %> 
            <%= link_to "Decline", friendship_path(sender_id: request.sender.id, receiver_id: current_user.id), method: :delete, class: "btn btn-danger" %> 
          </span>
        </article>
      <% end %>
    <% else %>
      <p>You haven't received any friend requests yet</p>
    <% end %>
  </div>

  <!-- Users sent friend requets-->
  <div class="col-xs-12 col-sm-12 col-md-6">
    <h2>Friend Requests Sent</h2>

    <% if @user.sent_friend_requests.any? %>
      <% @user.sent_friend_requests.each do |request| %>
      <p><%= request.receiver.email %></p>
    <% end %>
    <% else %>
      <p>You haven't sent any friend requests</p>
    <% end %>
  </div>
</section>

<!-- Friends -->
<section class="row">
  <div class="col-xs-12 col-sm-12 col-md-6">
    <h2>Friends List</h2>
    <% if @user.friends.any? %>
      <% @user.friends.each do |friend| %>
        <p><%= friend.email %></p>
      <% end %>
    <% else %>
      <p>No Friends Yet</p>
    <% end %>
  </div>
</section>

<!-- Users posts -->
<%= render "partials/posts" %>